### ISSUE TITLE
Which features should be put in "default" features?

### ISSUE THREAD

**Issue by Awen-hub** [Financial-Times/polyfill-library#1067]
## What

Which features should be put in "default" features?

## Details

I find that "Object.keys" is one of "default" features but "Object.values" isn't. In my opinion they are both used quite frequently. 
So Which features should be put in "default" features? And `
polyfillLibrary.getPolyfills({
    features: {
      'all': {
      }
    }
  })`
is not a suggestion and we are supposed to use "default" instead?

**Comment by JakeChampion** [comment]
Hi @Awen-hub,

Many times when we changed the polyfills included in `default` we would get many issues/questions/complaints about the change. We decided that we would have `default` be a legacy alias and not something we plan to change or update, instead users should explicitly request what they would like to have included or use an alias which has a known fixed-set of polyfills such as `es5`, `es6` etc.

We don't recommend using `all` because of how large the bundle would be and likely most of it would not be needed. For example, if creating a bundle of all polyfills for IE11 the size would be 66.5 megabytes.

**Comment by Awen-hub** [comment]
@JakeChampion  Thanks for your answer. And will a feature be put into `default` when you think it is stable and dose not need to update any more, such as `Object.values`?

**Comment by JakeChampion** [comment]
We won't be updating the `default` list with any more features, we would like to move users away from using it if possible. Instead we recommend to list out all the features explicitly or to use a set such as `es5`, `es6` etc - these are well-understood sets of features that will likely never change.

**Comment by Awen-hub** [comment]
> We won't be updating the `default` list with any more features, we would like to move users away from using it if possible. Instead we recommend to list out all the features explicitly or to use a set such as `es5`, `es6` etc - these are well-understood sets of features that will likely never change.

Thanks, I got it
