### ISSUE TITLE
Invalid timeZoneName on version 3.108.0 (which can be fixed downgrading to previous Polyfill version)

### ISSUE THREAD

**Issue by Nickinthebox** [Financial-Times/polyfill-library#1100]
We use Polyfill on production website without specifying the version (I know we should not have, lesson learned!) loaded from cdn.polyfill.io

We use sentry & trackJS to track errors on our websites and noticed a tremendous amount of errors on TrackJS with error name:
`Invalid timeZoneName`

This error is originating from various browser version including:
- Firefox 72 / 78 / ...
- Safari 11 / 13 / 14.0 ...

We used Browserstack to double check and we indeed had error in console log.

We finally changed the Polyfill version to the previous available on the CDN (v3.101.0) and all the errors vanished and everything is working fine again.

I don't know if this comes from the 3.108.0 version (or from another version between 3.101 and 3.108) however, I see that some browser seems to be excluded from Intl.DateTime stuff in the latest  3.108.0 compared to 3.107.1 ( commit https://github.com/Financial-Times/polyfill-library/commit/f570a97be095e5a90b7c93859a146405262dce35#diff-dad587b9f55bc3cd01f001ba0e9009ab2c3debcd8f246b4120c4de7296c540e1 by @romainmenke commited by @JakeChampion ) but 

NB: By the way anyone knows why https://polyfill.io/v3/polyfill.js?version=3.101.0 gives version 3.101 but https://polyfill.io/v3/polyfill.js?version=3.102.0 / https://polyfill.io/v3/polyfill.js?version=3.103.0 / https://polyfill.io/v3/polyfill.js?version=3.104.0 / till 3.107.1 ... all give version 3.108.0 ?

**Comment by romainmenke** [comment]
🤔 That should not happen.

> Safari 11 / 13 / 14 / ...

If the error happens in Safari 11 it might be because of an update to Intl?
Looking through that big config change for all Intl polyfills I don't see any dropping to a version Safari 11 would not receive a polyfill.

Can you provide a code snippet and the polyfill.io url you use?

**Comment by Nickinthebox** [comment]
```
<!DOCTYPE html>
<html lang="fr">
    <head>
        <script
            src="https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl&version=3.101.0"
        >
    </script>
    </head>
    <body>
    <script>
        var date = new Date(Date.UTC(2021, 05, 20, 12, 0, 0));
        var options = {timeZone: "Europe/Paris", year: "numeric", month: "long", day: "numeric"};
        document.write(date.toLocaleDateString('fr-FR', options));
    </script>
    </body>
</html>
```

vs

```
<!DOCTYPE html>
<html lang="fr">
    <head>
        <script
            src="https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl&version=3.108.0"
        >
    </script>
    </head>
    <body>
    <script>
        var date = new Date(Date.UTC(2021, 05, 20, 12, 0, 0));
        var options = {timeZone: "Europe/Paris", year: "numeric", month: "long", day: "numeric"};
        document.write(date.toLocaleDateString('fr-FR', options));
    </script>
    </body>
</html>
```

**Comment by Nickinthebox** [comment]
Sorry @romainmenke I cannot help more than sharing these snippets, I don't really know the polyfill project structure and/or if this comes from Intl.

The first snippet above works well on Firefox 78, Safari 11, ... but the second one is not working.

Both are working fine on Firefox 92, Safari 14.1, Chrome 93, ...

**Comment by romainmenke** [comment]
That is totally fine :)

I can replicate the issue with that snippet which is awesome!

This works for me with the latest version :

Polyfill list :

- Intl.DateTimeFormat.~locale.fr
- Intl.DateTimeFormat.~timeZone.golden

However it seems we had an unintended breaking change somewhere.

My best guess at this point is that we now polyfill `DateTimeFormat` in more browsers, regardless of config.
Intl polyfills have their own feature detection and with the latest releases these might apply to more browsers.
@longlho Do you have any insights here?

When polyfilled time zone data is required. This is why adding `Intl.DateTimeFormat.~timeZone.golden` "fixes" the issue.

```html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <script
            src="https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl.DateTimeFormat.~locale.fr,Intl.DateTimeFormat.~timeZone.golden&version=3.108.0"
        >
    </script>
    </head>
    <body>
    <script>
        var date = new Date(Date.UTC(2021, 05, 20, 12, 0, 0));
        var options = {timeZone: "Europe/Paris", year: "numeric", month: "long", day: "numeric"};
        document.write(date.toLocaleDateString('fr-FR', options));
    </script>
    </body>
</html>
```

@JakeChampion unsure how to resolve this one. Technically this seems too have been a breaking change which we should fix. But then we need to ship either `Intl.DateTimeFormat.~timeZone.golden` or `Intl.DateTimeFormat.~timeZone.all` each time `Intl.DateTimeFormat` is requested. (having both would then also no longer make sense)

**Comment by Nickinthebox** [comment]
If it helps, I have tried the snippets on Browserstack on the following versions:

Firefox 91: both snippets are working
Firefox 90: snippet with 3.108.0 is not working

Opera 63 : both snippets are working
Opera 62 : snippet with 3.108.0 is not working

Chrome 76: both snippets are working
Chrome 75: snippet with 3.108.0 is not working

**Comment by longlho** [comment]
The polyfills we wrote actually track stage-3 proposals for ECMA-402 which typically means 2 engines have shipped & next version of normative changes. The detection algorithm reflects that.

**Comment by romainmenke** [comment]
Sorry @longlho, I should have explained better how it is related to https://github.com/Financial-Times/polyfill-library/issues/1042

In that case the time zone data was missing. We resolved that by adding `Intl.DateTimeFormat.~timeZone.all` and `Intl.DateTimeFormat.~timeZone.golden` as separate features.

Some browser versions however have limited native `Intl` support and have time zone data.
When the polyfill isn't applied because of feature detection in `shouldPolyfill` some features would just work natively.
`Intl` isn't feature complete but when only older features are used it seems to work in some browser versions.

When `shouldPolyfill` is updated it appears to break in versions it previously worked.
This is what happened here I think.

---------

Still unsure if this is something we should fix/handle.
Fixing it would mean forcing `Intl.DateTimeFormat.~timeZone.all` to everyone who requests `Intl.DateTimeFormat`, which is a lot of extra data.

Maybe for now it is ok not to handle it here but advice adding `Intl.DateTimeFormat.~timeZone.golden`.

---------

@Nickinthebox Have you had a chance to test the latest version of polyfill.io with `Intl.DateTimeFormat.~timeZone.golden`?
That should fix your issues.

**Comment by longlho** [comment]
yeah timezone is optional, similarly to how IE11 ships DateTimeFormat without timezone data so I think it's probably a documentation issue instead of forcing tz data in every instance.

**Comment by romainmenke** [comment]
@Nickinthebox The builder has been updates :
