### ISSUE TITLE
String.prototype.trim incorrect safari version range

### ISSUE THREAD

**Issue by cdaringe** [Financial-Times/polyfill-library#1133]
### Problem

String.prototype.trim claims `safari = "<12.1"`, which appears incorrect

## Details

- MDN claims support: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
- https://caniuse.com/?search=trim

I suspect it should be `<5` vs `<12.1`!

Please assert and we will send a patch

**Comment by JakeChampion** [comment]
Hi, this is due to the fact the version of unicode used in ecmascript was updated and changed what was defined as whitespace - that whitespace definition is used in string.prototypr.trim, which meant older browsers had a spec non compliant implementation, which is why we polyfill those versions.

This is the commit which updated the spec https://github.com/tc39/ecma262/pull/300

**Comment by cdaringe** [comment]
Ouch! https://en.wikipedia.org/wiki/Whitespace_character#Unicode

must have been rough doing that diff
