### ISSUE TITLE
Symbol Edge versions incorrect

### ISSUE THREAD

**Issue by EECOLOR** [Financial-Times/polyfill-library#130]
The versions here do not match the versions in the `config.json` files:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

2 examples:
[`replace`](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Symbol/replace/config.json): `"edge": "*"`
[`match`](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Symbol/match/config.json): `"edge": "*"`

I am not sure what you guys use as a source for the actual versions.

A workaround for the short term would be to add feature detection to my api request.

**Comment by EECOLOR** [comment]
The errors we received in our error tracker:

`TypeError: Cannot redefine property: replace`
`TypeError: Cannot redefine property: match`

Some UA strings: 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393`
`
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
`

**Comment by JakeChampion** [comment]
Hi @EECOLOR, we looked into the support for those symbols on MDN but the page is not helpful, it says "yes" instead of saying which version the support was added in.

![image](https://user-images.githubusercontent.com/1569131/53184628-4ad14880-35f5-11e9-90dd-dfa168d3c8b1.png)

We also tried to test in Edge ourselves but the oldest version of Edge we have available is 15.
Do you happen to know which version it was added in?

**Comment by EECOLOR** [comment]
I dug through the error logs and the lowest versions were:

`match`: 15
`replace`: 14

I tried to find something on the internet, but the documentation for the MDN table states: "Supported, but version unknown" when the value is `true` (`Yes`).

So for now I think it's safe to list the `match` and `replace` version as `<15` and `<14`. Unfortunately browserstack does not allow me to check on the older versions.

**Comment by EECOLOR** [comment]
:+1:
