### ISSUE TITLE
[bug] IE11 - Cannot redefine non-configurable property 'find'

### ISSUE THREAD

**Issue by hstaniszewski** [Financial-Times/polyfill-library#178]
## What
In the IE11 browser script throws an error `Cannot redefine non-configurable property 'find'` when trying to use polyfill with `features=default,es6` on page, which already has the `Array.prototype.find` with attribute `configurable: false` defined.

## Details
I believe that polyfill should not cause an error in this case. Here is a link with reproduction example:
https://jsfiddle.net/xk8afqbu/

Environment:
Browser: Internet Explorer 11

**Comment by JakeChampion** [comment]
`Array.prototype.find` should be configurable according the the ECMAScript-262 specification (https://tc39.github.io/ecma262/#sec-createmethodproperty).

I would recommend not having multiple sources of polyfills, as they may not interact with each-other correctly, especially if one of the sources is making an incorrect polyfill such as making the property non-configurable.

IE 11 does not support `Array.prototype.find` which is why the polyfill-library would be trying to define a `find` property on `Array.prototype`.

The only way for polyfill-library to work around this type of issue would be to wrap each polyfill in a feature-detect, which would increase the size of the polyfill bundle that it creates.

If using the polyfill-service you can configure it to only wrap a feature-detect around `Array.prototype.find` like so: 
https://polyfill.io/v3/polyfill.js?features=default,es6,Array.prototype.find|gated

If using polyfill-library it would be like so:
```js
const polyfillLibrary = require('polyfill-library');

const polyfillBundle = polyfillLibrary.getPolyfillString({
	uaString: 'ie/11',
	minify: true,
	features: {
		'es6': {},
		'default': {},
		'Array.prototype.find': { flags: ['gated'] }
	}
}).then(function(bundleString) {
	console.log(bundleString); // string of JS polyfills
});
```
