### ISSUE TITLE
[feature-request] `Custom Properties` for IE11

### ISSUE THREAD

**Issue by nuxodin** [Financial-Times/polyfill-library#258]
## What
A polyfill for Custom Properties support targeting IE11
https://github.com/nuxodin/ie11CustomProperties

## Details
Many people are prevented from using custom properties because IE11 does not support them yet.
The Proposed Script will polyfill Custom Properties almost completely.

**Comment by joeworkman** [comment]
Another option is https://jhildenbiddle.github.io/css-vars-ponyfill

**Comment by JakeChampion** [comment]
Hi sorry for taking a while to get to this issue, polyfill-library does not aim to polyfill CSS features such as this because they are not yet possible to do correctly and/or permanently, you can see this with the polyfill for Custom Properties as it has listed the [limitations here](https://github.com/nuxodin/ie11CustomProperties#small-limitations).

When CSS Houdini has landed in stable browsers, polyfill-library may start supporting CSS polyfills.

**Comment by nuxodin** [comment]
Other polyfills also have limitations.
https://github.com/juggle/resize-observer/#limitations
I implemented relatively large projects without having to pay much attention to IE11 regarding CSS variables.
