### ISSUE TITLE
[bug/feature-request] handling chromium based edge

### ISSUE THREAD

**Issue by thisguychris** [Financial-Times/polyfill-library#316]
## What

Latest chromium-based Edge is being tagged as normal Edge?

## Details

Hi 👋🏻, I've been using this service before, I'm glad this is still well maintained. 😊

I'm interested in the automatic generation, and plan to host this on our own server, just wondering how you handle the latest Edge with chromium as it's based? To describe the issue:

Going to https://polyfill.io/v3/polyfill.min.js
gives substantial polyfill, even the underlying Chrome engine is at 80.0 (this should be blank)

I'm currently using Chromium Edge v80 with UA:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3956.0 Safari/537.36 Edg/80.0.328.0

I propose to use it's chromium version instead? Using v2 URL gives me ie/80.0

```
 * UA detected: ie/80.0.0
 * Features requested: default
```

Here's what I'm seeing in v2 polyfill service:
![Alt text](https://monosnap.com/image/ijk5icG7N9BCTaKlUgA3Kw3KZPbUVn)

and here's v3:
![Alt text](https://monosnap.com/image/RbLVLKmilFkYytAf9eJQVbiHOBs27U)

**Comment by JakeChampion** [comment]
Good idea @thisguychris, we should use the chromium version number instead here. V3 currently parses this as edge version 80, I guess we should alias Edge versions above version 18 to chrome.

**Comment by thisguychris** [comment]
@JakeChampion 👋🏻, let me know if I can help. If you can point me to where’s the logic at, I can send PR on your way. I can help with testing too.

**Comment by JakeChampion** [comment]
I've thought about this some more, since we have automated testing for Edge 80, we can keep the user-agent detection as for Edge 80 as Edge 80 (not aliasing to Chrome), that way we can fix any Edge specific issues that may come up. Edge is 80 is based off of Chromium but can decide which features to enable and disable.

Samsung Internet is based off of Chromium but does have different features enabled and disabled, for instance they enabled WebXR and in the past they did disable ECMA402 Intl support.

We have nightly automation which updates the polyfill configuration for each browser, so Edge 80 should be getting the correct set of polyfills now
