### ISSUE TITLE
Does not work with Picture element ie11

### ISSUE THREAD

**Issue by rgfx** [Financial-Times/polyfill-library#50]
Maybe am doing something wrong, but it doesn't seem to work with the html5 picture element in IE11. However it does work with the standard polyfill Picturefill https://cdn.rawgit.com/scottjehl/picturefill/3.0.2/dist/picturefill.min.js

Here is my sample https://codepen.io/rgfx/pen/GQLgNP

**Comment by JakeChampion** [comment]
This was likely because the polyfill.io url did not include HTMLPictureElement in the features query parameter list like this https://polyfill.io/v3/polyfill.min.js?features=HTMLPictureElement.

I've tested https://polyfill.io/v3/polyfill.min.js?features=HTMLPictureElement in IE11 and it works

https://jsbin.com/fokakiquki/edit?html
![in](https://user-images.githubusercontent.com/1569131/78462860-3b647000-76ce-11ea-960f-5908b378c0ab.gif)
