### ISSUE TITLE
HTMLTemplateElement/polyfill.js missing

### ISSUE THREAD

**Issue by alexkadis** [Financial-Times/polyfill-library#555]
## What

The `polyfills/HTMLTemplateElement/polyfill.js` file is not in the repository and therefore `HTMLTemplateElement` is not supported.

## Details
The file is [completely missing from the history](https://github.com/Financial-Times/polyfill-library/commits/master/polyfills/HTMLTemplateElement), including the original commit 151cd805222f81535d0617b0b52bb094f903b21d.

**Comment by JakeChampion** [comment]
It's gets downloaded as a dependency via npm and installed during our postinstall npm run-script, it doesn't live inside this repository because it is a third-party polyfill and we can update it better using this approach.

You can see the polyfill does exist by using the polyfill.io service https://polyfill.io/v3/polyfill.js?features=HTMLTemplateElement|always
