### ISSUE TITLE
[Bug] Webkit 10 doesn't support Symbol.iterator

### ISSUE THREAD

**Issue by TLib** [Financial-Times/polyfill-library#779]
System: iOS 9.3.5
Browser Safari 9.0

The mentioned browser doesn't support Symbol.iterator. We have many issues in our Sentry log (>50k in 4 days). I can't test it, because i had no device with iOS9 but i checked the support on https://caniuse.com/#search=symbol.iterator 

After that i saw, that in
https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Symbol/iterator/config.toml the MacOS Version also has the wrong version number.

**Comment by romainmenke** [comment]
Manually tested this on iOS 9 with Browserstack.

- no polyfill included
- only the test was run

The test seems to pass.

@TLib Does this error still happen because I can't reproduce the issue :/

<img width="925" alt="Screenshot 2021-02-20 at 23 40 17" src="https://user-images.githubusercontent.com/11521496/108610315-0ab82280-73d5-11eb-886b-0723dbd52a0f.png">

**Comment by TLib** [comment]
Thanks for your feedback. I can confirm, that the errors in our Sentry are gone.
